version: "3"

services:

  database:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo

  setup:
    image: rust:1-bookworm
    volumes:
      - ./:/data/
    environment:
      - SKIP_DOCKER=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
      - DATABASE_URL=postgres://postgres:password@database/todo
    depends_on:
      - database
    entrypoint: ["bash", "-c", "cargo install sqlx-cli --no-default-features --features postgres && sqlx migrate run --source /data/migrations/"]

  todo-rs:
    image: ghcr.io/andreanidouglas/todo-rs:latest
    ports:
      - "32100:8000"
    links:
      - database
    depends_on:
      database:
        condition: service_started
      setup:
        condition: service_completed_successfully
    environment:
      - APP_ENVIRONMENT=production
      - APP_DATABASE__USERNAME=${DATABASE_USER}
      - APP_DATABASE__PASSWORD=${DATABASE_PASSWORD}
      - APP_DATABASE__HOST=${DATABASE_HOSTNAME}
      - APP_DATABASE__PORT=${DATABASE_PORT}
      - APP_DATABASE__DATABASE_NAME=${DATABASE_NAME}

